### ISSUE TITLE
Mobile issues

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-theme-novela-1#5]
Seems like on mobile we have 2 issues:

1. List page displaying like desktop
2. Subsribe button broken

👉 https://github.com/forestryio/hugo-theme-novela/issues/7

**Comment by mountainbug95** [comment]
@regisphilibert I've fixed the newsletter CTA issue. I was not able to recreate the layout issue for the Samsung Galaxy S8+, and Galaxy Note 9 in browserstack so I believe that is a nonissue now.

**Comment by DirtyF** [comment]
Fixed in https://github.com/forestryio/hugo-theme-novela/pull/30
